name: MySwarm 
alias: dcos1
active_cluster: all
certpath: /Users/meetri/.sage/keys/dcos/
clusters:
    - { name: "cloud1", certpath: "/Users/meetri/.sage/keys/dcos" }
    - { name: "local", certpath: "" }
hosts:
  - { alias: "swarm-node1", cluster: "cloud1", host: "tcp://mesos-node1.ptechtoolz.com:2376" }
  - { alias: "swarm-node2", cluster: "cloud1", host: "tcp://mesos-node6.ptechtoolz.com:2376" }
  - { alias: "swarm-node3", cluster: "cloud1", host: "tcp://mesos-node7.ptechtoolz.com:2376" }
  #- { alias: "local", host: "tcp://192.168.59.104:2376" }
  #- { alias: "pi", host: "tcp://raspberry.pi:2376","binary":"/Users/meetri/.dvm/bin/docker/1.11.0/docker","certpath":"" }
